### ISSUE TITLE
Some TextLinks not working.

### ISSUE THREAD

**Issue by m-levi** [michaelloistl/ContextLabel#11]
I'm having an issue where an array of textLinks is created, but the label doesn't seem to recognize them. Any ideas? 

Here's my code: 

```
 let s = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sit amet rutrum lorem. Nullam a purus at ex dictum vehicula sit amet sit amet metus. Integer nec eros at felis mattis tempor. Morbi id sem semper, posuere leo non, semper ex. Etiam venenatis odio quam, sed pulvinar augue sagittis at."
        label.text = s

        let words = s.componentsSeparatedByString(" ")
        
        var textLinks = [TextLink]()
        for word in words {
            let textLink = TextLink(text: word, action: test)
            textLinks.append(textLink)
        }
                
        label.textLinks = textLinks

```

![screen shot 2016-03-13 at 1 39 53 pm](https://cloud.githubusercontent.com/assets/6935732/13728432/21cd1a46-e921-11e5-98c8-994e344b127c.png)

**Comment by michaelloistl** [comment]
Text links finds and returns the range of the first occurrence of a given string within the receiver. Your example repeats words multiple times and therefore those aren't selected. Your example isn't anything that would happen in the real world.

**Comment by m-levi** [comment]
Ah, gotcha. Sorry for the confusion. 

Is there any way to have it where I could have duplicate words?

**Comment by michaelloistl** [comment]
Will add this in the next update. Tracking that issue here #12

**Comment by m-levi** [comment]
Thanks!! Just curious, any idea on when the next update might be?

**Comment by michaelloistl** [comment]
Haven't scheduled anything yet. Will have a think how to implement that best over the next few days. Will try to get it in by end of next week. No promises though :)

**Comment by m-levi** [comment]
Awesome. Thanks :D
