### ISSUE TITLE
Regex matching still fails for text with emoji

### ISSUE THREAD

**Issue by demonar** [michaelloistl/ContextLabel#14]
@michaelloistl i updated my code with the latest version, and i'm still getting errors on the ranges for the text that contains emoji, i checked the code and see that there's an error:

```
let length: Int = text.characters.count
if let matches = regex?.matchesInString(text, options: .ReportCompletion, range: NSMakeRange(0, length)) {
            for match in matches {
                let matchRange = match.range
                let matchString = NSString(string: text).substringWithRange(matchRange)                
                if matchRange.length > 1 {
                    rangesForLinkType.append(LinkRangeResult(linkDetectionType: linkType, linkRange: matchRange, linkString: matchString, textLink: nil))
                }
            }
        }
```

on that block, you're handling the ranges with an NSString, but the regex?.matchesInString method is using a String to create the matches, that results in the same issue we have, i'll investigate on my side if there's a way to move everything to NSString and avoid this.

**Comment by michaelloistl** [comment]
@demonar would you have a failing test?

**Comment by demonar** [comment]
Any string that has emoji and some hashtags, mentions or links, check that, something like:

"Going for a walk @ the park, 👣👟🐾🌳  #footing #sport #awesomedayatthepark ☀️🕶  http://weatherchannel.com"
