### ISSUE TITLE
Any plans to make this component work under Swift 3?

### ISSUE THREAD

**Issue by weyert** [michaelloistl/ContextLabel#15]
Any plans to make this component work under Swift 3?

**Comment by michaelloistl** [comment]
Yes, this week.

**Comment by weyert** [comment]
Fantastic, happy days 💃

**Comment by weyert** [comment]
@michaelloistl Looks like line 491 the optional UIColor causes an exception which can be fixed by force casting it now it runs as expected

**Comment by michaelloistl** [comment]
@weyert thank you for your feedback.
The swift 3 branch is still work in progress. Once it's completed, it will be merged into master.

**Comment by michaelloistl** [comment]
@weyert the swift-3 branch would now be ready for testing if you want. I have just to update the readme as the delegates have now been replaced by functions.

**Comment by thebaer** [comment]
@michaelloistl What replaces the `ContextLabelDelegate` in these updates? I'm specifically looking for how to handle the click event (was previously using `contextLabel(contextLabel: ContextLabel, endedTouchOf text: String, with linkRangeResult: LinkRangeResult)` for this)

**Comment by michaelloistl** [comment]
@thebaer, sorry for the delay in updating the readme. Hope getting it done this week.

The delegate is now replaced with a closure that is part of the initialiser.

````
let _label = ContextLabel(frame: CGRect.zero, didTouch: { (touchResult) in
            switch touchResult.state {
            case .began:
                ...
            case .ended:
                ...
            default:
                break
            }
        })
````

````
struct TouchResult {
    public let linkResult: LinkResult
    public let touches: Set<UITouch>
    public let event: UIEvent?
    public let state: UIGestureRecognizerState
}
````

````
struct LinkResult {
    public let detectionType: ContextLabel.LinkDetectionType
    public let range: NSRange
    public let text: String
    public let textLink: TextLink?
}
````

**Comment by thebaer** [comment]
No worries at all, thanks for the info and update!
