### ISSUE TITLE
Not working on already attributed text

### ISSUE THREAD

**Issue by igorkulman** [michaelloistl/ContextLabel#24]
I noticed the `ContextLabel` is not working when I assign `attributedText` instead of `text`. The text is displayed but the link detection is not executed. Any chance you can support that?

The problem that I am trying to solve is that I have texts in a chat displayed `ContextLabel`, some may contain links, and in addition to that, I need to highlight part of the text. The preferred solution would be to do the attributing myself and give the already attributed text to `ContextLabel`.

**Comment by michaelloistl** [comment]
I had a similar use case recently and did the highlighting part in:

```
contextLabel.modifiedAttributedString = { (attributedString) in
  var _attributedString = attributedString

  // Modify attributes

  return _attributedString
}
```

Have you considered that?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by igorkulman** [comment]
That is a great solution, thanks. I should have read the README more carefully.
