### ISSUE TITLE
regex recognition with emoji is not working

### ISSUE THREAD

**Issue by demonar** [michaelloistl/ContextLabel#3]
using this text as an example: "Algún día conquistaré el mundo 😼🌎 @pompous.albert ❤️ @fotos4patas 🐾 #fotos4patas #cat #gato #world" your regex recognition will fail as it's giving a wrong text length, this happens because NSRegularExpression is using NSString internally and giving you NSRange results based on the NSString count (97 chars for String and 101 chars for NSString).

check this link for details:

http://stackoverflow.com/questions/27880650/swift-extract-regex-matches

**Comment by mamouneyya** [comment]
I cannot find anything in your commit related to this issue, which sadly still exits. I could fix it on my side using @demonar 's suggested modifications, with a small addition in line # 570 :

    let matches = dataDetector.matchesInString(plainText, options: NSMatchingOptions.ReportCompletion, range: NSMakeRange(0, count(plainText)))

which is to use the utf16 string count:

    let matches = dataDetector.matchesInString(plainText, options: NSMatchingOptions.ReportCompletion, range: NSMakeRange(0, plainText.utf16.count))

**Comment by michaelloistl** [comment]
Thank you @mamouneyya.
Will check & fix that later today.

**Comment by mamouneyya** [comment]
Thanks man!

**Comment by michaelloistl** [comment]
Started to write various tests yesterday and discovered that the solution proposed from @demonar (conversion between Range<Index> and NSRange) would fail in some cases. Hope to have all properly tested and updated in a few days.

**Comment by demonar** [comment]
It happens when using NSString methods, it's hard to keep the consistency when using ranges.

**Comment by demonar** [comment]
@michaelloistl if possible please let me know the tests you are running and if i can help you on anything to fix it, i'm running this with a lot of cases that could help us on fixing it completely

**Comment by michaelloistl** [comment]
Have updated the develop branch to use NSRange throughout without converting to String<index> as that causes issues with some strings including emojis. I will update the read and merge with master later today. @demonar maybe you can run your tests against the current develop branch / add any test cases that you think are missing. I have also changed the regex pattern as the old one failed in some tests.
