### ISSUE TITLE
How to use ContextLabel inside TableView that associates with a UITapGestureRecognizer

### ISSUE THREAD

**Issue by ZihangYin** [michaelloistl/ContextLabel#6]
Hey, I have one question about how to use this context label. 

Now, I have a UITableView, each cell contains a ContextLabel. A UITapGestureRecognizer is added to the UITableView so that I can add tap gesture to cell's subview. Now the context label does not response any more. What would be the correct way to do this.

Thank you in advance.

**Comment by michaelloistl** [comment]
Without knowing your code ... have you set the UIGestureDelegate with ````gestureRecognizer(_:shouldRecognizeSimultaneouslyWithGestureRecognizer:)````?
