### ISSUE TITLE
Highlighting not working on texts with emojis

### ISSUE THREAD

**Issue by Jamal1337** [michaelloistl/ContextLabel#7]
Hey, first of all thanks for providing this code snippet. Everything works fine except the one case with emojis.

If I have a Text with emojis in the middle and some hashtags at the end of the sentence, the higlighting is not working correct anymore. I found this, but am not able to get it working:
http://stackoverflow.com/questions/30400969/how-do-i-highlight-text-in-a-string-that-contains-emojis-in-swift

**Comment by michaelloistl** [comment]
Thank you for adding this issue. Will check and fix asap.

**Comment by mamouneyya** [comment]
This actually related to issue #3 which can be also fixed using @demonar 's fix.
